### ISSUE TITLE
Seeing a bunch of anonymous tasks

### ISSUE THREAD

**Issue by garretthyder** [10quality/gulp-wpmvc#10]
Hi @amostajo not sure if this is expected but updating to the latest and running `gulp build` I'm seeing a bunch of anonymous tasks;
```
[14:19:52] Finished '<anonymous>' after 16 ms
[14:19:52] Finished 'scripts' after 17 ms
```

**Comment by amostajo** [comment]
@garretthyder Yes this is fine.

**Comment by amostajo** [comment]
Gulp 4 displays more stuff than gulp 3

**Comment by garretthyder** [comment]
Ah good to know, thanks @amostajo
