### ISSUE TITLE
Avoid creating app.js during gulp build

### ISSUE THREAD

**Issue by garretthyder** [10quality/gulp-wpmvc#13]
Hello @amostajo hope you are well.

This might be a simple existing option/config that I'm unaware of, but in short I'd like my gulp build not to create the app.js file as I include my scripts individually as not all are needed in every context.

When I run `gulp build` my sass is generated individually without an app.css, but my JS generates the individual files but also generates an app.js with them all together. I don't need nor care for this app.js file.
How do I suppress it's generation and inclusion in my plugin.zip.

Much appreciated

**Comment by amostajo** [comment]
There is an option to add to the pipeline to omit files from the final build.

Inside `gulpfile.js` after the `// START - CUSTOM TASKS` you can add this to omit the `app.js` from being minified, which will also exclude it from the final build:

```javascript
config.jsminAppend = ['!./assets/js/app.js'];
```

**Comment by garretthyder** [comment]
Thanks @amostajo greatly appreciated
