### ISSUE TITLE
Separate admin assets compilation.

### ISSUE THREAD

**Issue by amostajo** [10quality/gulp-wpmvc#2]
Allow admin related content to be compiled under:

* `/assets/raw/js/admin`
* `/assets/raw/css/admin`

Both should create files `admin.js` and `admin.css`

For SASS, make it so, if `admin.sass` or `admin.scss` is defined, then it is generated inside `admin` folder.

**Comment by garretthyder** [comment]
Would be interesting to suppot any foldername so;
/assets/raw/js/editor would create the editor.js file

**Comment by garretthyder** [comment]
❤️love it @amostajo, thanks

**Comment by amostajo** [comment]
Sass css files are added to assets on the second run.
